// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace GAConsoleAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Type"), LoadColumn(0)]
        public string Type { get; set; }


        [ColumnName("Message"), LoadColumn(1)]
        public string Message { get; set; }


    }
}
